### ISSUE TITLE
Topic looks too short. Having more specific topics is recommended.

### ISSUE THREAD

**Issue by maxweissboeck** [cedalo/streamsheets#19]
Why is this warning poping up? My topics are at least 8 characters long, that is enough!

**Comment by ralight** [comment]
Could you give a hint as to where you are seeing this happen?

**Comment by cleancoderocker** [comment]
This happens when one of the parts of an MQTT topic has a length < 2 and is displayed as warning in the notification center. It was a requirement from the QA department, but we should discuss again whether this warning makes sense.

**Comment by cleancoderocker** [comment]
The idea was to promote a hierarchical topic structure (connector, consumer, producer). But we are open for discussion here. // @evlach @TizianCedalo

**Comment by evlach** [comment]
Let me try to recall some background on this. If I am not mistaking we introduced that was because users were getting confused in relation to the base topic (topic defined on connector level). However, we are planning anyway to improve consumer ui form (show resulting topic) and maybe this is enough and we do not need the warning anymore. I would love to hear opinions from the community on that.

**Comment by maxweissboeck** [comment]
I'm coming from NodeRed, sending a message with topic "wasserstand" and it is handled and displayed all correct.
But ehenever I edit the Consumer with topic "wasserstand", I get this nasty warning message.
Why sould my topic contain a "/" ? I tihnk not this is a requirement in MQTT protocol.
I can understand very well that you warn for topics shorter then 2, but why should a topic consist always of parts? I see this is usefule if your system is big so you need a naming schema, but for some 20 values it's overkill.

**Comment by evlach** [comment]
We will push soon an improved approach - stay tuned ;)

**Comment by evlach** [comment]
Should be fixed now with 135692abda1f91a7cf810388f59019c1d009e2f5
