### ISSUE TITLE
#INVALID_PATH error for WRITE() function after upgrade to 1.6-milestone from 1.5

### ISSUE THREAD

**Issue by seb-koch** [cedalo/streamsheets#47]
### Description

The following formula works fine in 1.5 but throws a "#INVALID_PATH" error when upgrading the container to 1.6. I assume there were breaking changes, i did not find anything in the release notes and i did not find the docs for 1.5 so i could compare the changes in the WRITE function.

### Steps to Reproduce

1. Create v1.5 based machine with formula: =WRITE(OUTBOXDATA("Message"),READ(INBOXDATA(,)))
2. Upgrade container to 1.6-milestone or 2.0 milestone
3. Error #INVALID_PATH will appear

**Expected behavior:**

That the function is backwards compatible.

**Actual behavior:**

Error is thrown.

**Reproduces how often:**

100%

### Versions

Works in v1.5 and breaks with 1.6-milestone

**Comment by TizianCedalo** [comment]
Hi seb-koch,

Thank you for the post! We are investigating the issue. I will come back to you as soon as we know something.

For now, you can use SUBTREE() instead of READ(). Check the [docs ](https://docs.cedalo.com/functions/streamsheet/subtree.html?highlight=subtree)for details. 

_=WRITE(OUTBOXDATA("Message"),SUBTREE(INBOXDATA(,)))_

Let me know if that fixed your problem!

**Comment by seb-koch** [comment]
Perfect, works like a charm. Thanks

**Comment by TizianCedalo** [comment]
Hi seb-koch,

I have researched what the problem is: Using READ() in this context should have never worked. We have fixed a bug in 1.6 concerning this issue. 
As mentioned SUBTREE() is the way to go. 
We apologize for the inconvenience!
